name: macOS Certs
description: GitHub action to create a keychain and import macOS certificates for publishing macOS apps.
author: Mark Skelton
branding:
  icon: lock
  color: orange
runs:
  using: "composite"
  steps:
    - name: Add macOS certs
      shell: bash
      run: |
        chmod +x ${GITHUB_ACTION_PATH}/add-macos-certs.sh
        ${GITHUB_ACTION_PATH}/add-macos-certs.sh
